### ISSUE TITLE
layouts: above, beside, align etc

### ISSUE THREAD

**Issue by brainrake** [paf31/purescript-drawing#12]
As seen on http://docs.racket-lang.org/teachpack/2htdpimage-guide.html

Would need a `size` function that returns the width/height of a `Drawing`, based on the size of `Shape`s and applied transforms. Eg `above` would then create a `Many` with the second Drawing translated to below the first.
Outlines, shadows and text complicate things a bit.

If you feel this is within scope of the library, I could give it a shot.

**Comment by brainrake** [comment]
Also, getting the size of a rotated `Drawing` depends on what `Shape`s it includes. Might be a hard one, for starters they could all be treated as rectangles.

**Comment by paf31** [comment]
Sounds good to me. Approximating using a single bounding rectangle seems like a fine approach to me.

Another option is to use something like an _envelope_ from Haskell's `diagrams` although obviously that is more involved.

**Comment by brainrake** [comment]
I see `Rectangle` and `Circle` have explicit positioning. Any reason not to use `Translate` instead? In the case of `Path`, `(0, 0)` could be assumed the top left corner.

**Comment by paf31** [comment]
Yeah I thought about that. I think it'd be fine that way.

**Comment by brainrake** [comment]
Cool, on it.

**Comment by brainrake** [comment]
Not much sense for `Composite` then...

**Comment by jmatsushita** [comment]
Any plans to revive this issue and PR? I'm just getting started with `purescript-drawing` and `purescript` and AFAIA there aren't yet any facilities to help with layout ?

**Comment by paf31** [comment]
This sounds like it would make a good library atop `drawing` actually. In any case, I think it would make sense to prototype it outside this library first.
