### ISSUE TITLE
Split out Drawing.Color?

### ISSUE THREAD

**Issue by sharkdp** [paf31/purescript-drawing#17]
In my opinion, the `Drawing.Color` module is very useful in its own right. I went ahead and created an initial version of a [purescript-colors](https://github.com/sharkdp/purescript-colors) package which has a similar API to `Drawing.Color` (and uses your HSV -> RGB conversion algorithm, I hope that's fine).

The idea is to further extend the functionality and to make it compatible with different use cases (not just Canvas drawing).

If you think this is a good idea, I would continue along this path and eventually send a PR to replace `Drawing.Color` with the corresponding module from `purescript-colors`.

**Comment by paf31** [comment]
:+1: Sounds great!

The conversion routines were lifted from Wikipedia actually :smile:
