### ISSUE TITLE
Semigroup instance for Point ?

### ISSUE THREAD

**Issue by jmatsushita** [paf31/purescript-drawing#24]
Not sure if that would be a good idea and would break some abstractions, but it would be useful to be able
instead of:
```
-- p, q, r :: Point
r = { x: (p.x + q.x), y: (p.y + q.y) }
```

to do 
```
r = p <> q
```

Or maybe I'm just too lazy :)

**Comment by paf31** [comment]
This doesn't seem like a very canonical instance to me. Why prefer this over one of the many other lawful instances?

**Comment by jmatsushita** [comment]
Sorry, beginner here... I tried to create a Semigroup instance but I couldn't since Point is a Type and not an ADT. Would I have to create my own Point' ? Or do you mean something else?
